name:                puregb
version:             0.1.0.0
github:              "githubuser/puregb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/puregb#readme>

dependencies:
- base >= 4.7 && < 5
- GLFW-b == 3.3.0.0
- gl
- raw-strings-qq
- bytestring
- QuickCheck == 2.14.2
- path
- array
- filepath
- utf8-string
- file-embed
- containers
- microlens
- microlens-platform

library:
  source-dirs: src

executables:
  puregb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puregb

tests:
  puregb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puregb
